### ISSUE TITLE
Add some UI to let the user know where are the limits of the arm movement

### ISSUE THREAD

**Issue by aornelas** [SpaceVR-O1/Human#18]
Otherwise, you're continually prodding the air to find the limits, like feeling around in a dark room.

**Comment by aornelas** [comment]
* black circle for center of room
* white sphere towards front of Human
* red spheres when controller is out of range

**Comment by SpaceVR-O1** [comment]
Did we fix the merge that removed this code from master?

**Comment by aornelas** [comment]
@SpaceVR-O1 nope; that's why this issue is still open

**Comment by aornelas** [comment]
Fixed and committed to master
