### ISSUE TITLE
Figure out valid input ranges for Kinova arm

### ISSUE THREAD

**Issue by SpaceVR-O1** [SpaceVR-O1/Human#2]

**Comment by aornelas** [comment]
WIP: https://github.com/SpaceVR-O1/Human/compare/arm-range-of-motion-values

Includes mechanism to easily experiment with different position values (input values from Unity IDE in Play Mode and then VIVE trigger moves arm to those) and two positions: RestingPosition (arm down) and RaiseTheRoof (arm up). These positions are mapped to a touchpad down and touchpad up click, respectively.

Before adding more values, need to devise a cleaner way to manage the different positions in the code (Position class with instances per position, perhaps?) so we can easily pass in a single position argument to `DoMoveArm`.

**Comment by aornelas** [comment]
Position class added for better position management!
https://github.com/SpaceVR-O1/Human/commit/001171ec8745a648cdfafd65d844a9886d41fe00
