### ISSUE TITLE
Stream Human 360 video across the network

### ISSUE THREAD

**Issue by aornelas** [SpaceVR-O1/Human#29]

**Comment by aornelas** [comment]
https://forum.unity3d.com/threads/stream-video-through-network.464693/

**Comment by aornelas** [comment]
http://answers.unity3d.com/questions/1349462/unity-simple-client-server-video-streaming-using-r.html

**Comment by aornelas** [comment]
alternatively, buy a Unity asset that enables video streaming (just need to make sure it's compatible with Ricoh Theta stream)... e.g.: https://www.assetstore.unity3d.com/en/#!/content/68030

**Comment by aornelas** [comment]
another interesting angle: https://github.com/theta360developers/ThetaWifiStreaming

**Comment by aornelas** [comment]
https://hackaday.io/project/5077-metaverse-lab/log/30947-ricoh-theta-s-360-streaming

**Comment by SpaceVR-O1** [comment]
Using NetworkTransport (missing serialization code): https://stackoverflow.com/questions/31269550/streaming-webcamtexture-with-new-unity-5-1-transport-layer-api

Deprecated WebCamTexture streaming example: http://answers.unity3d.com/questions/410504/live-webcam-stream-in-unity.html

**Comment by SpaceVR-O1** [comment]
WebRTC Unity Asset: https://www.assetstore.unity3d.com/en/#!/content/47846

**Comment by SpaceVR-O1** [comment]
WebRTC Video Chat Unity Asset: https://www.assetstore.unity3d.com/en/#!/content/68030

Key feature: "stream remote webcam images into textures and onto 3D objects"

**Comment by OpenSourceIronman** [comment]
WebRTC  - https://codelabs.developers.google.com/codelabs/webrtc-web/#0
Vantrix Camera http://blog.vantrix.com/aqua
Vantrix product offering - https://vantrix.com/products/vantrix-360/

Theta S Live Streaming http://theta360.guide/community-document/live-streaming.html
Theta S software for Mac - 

Live Plabet 3D camera - https://www.liveplanet.net/

**Comment by SpaceVR-O1** [comment]
UWebcam Unity Asset: https://www.assetstore.unity3d.com/en/#!/content/91693

**Comment by SpaceVR-O1** [comment]
https://theta360blog.wordpress.com/tag/livestreaming/

**Comment by aornelas** [comment]
done; just need to tweak asset options for better(ish) quiality and merge
