### ISSUE TITLE
Add home position command

### ISSUE THREAD

**Issue by SpaceVR-O1** [SpaceVR-O1/Human#3]

**Comment by aornelas** [comment]
Once we fix #4, we can simply define our own home position (RestingPosition, most likely) and bind it to a VIVE button.

**Comment by aornelas** [comment]
... actually, the HOME button in the Kinova joystick does more than just `MoveArm(Position)`, since it INTERRUPTS other movements AND moves to a reset position.

Thus, bring it, DLL. BRING IT.

**Comment by aornelas** [comment]
Possible workaround if exposing the home function from the DLL doesn't work out: close the device and reinit the API when with the VIVE home 🤔

**Comment by aornelas** [comment]
This was implemented already (mapped to grip button)
